[package]
name = "create-github-app-token"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
jsonwebtoken = "7.2"
serde = { version = "1.0", features = ["derive"], default-features=false }
surf = "2.3"
